# test

name: tansacs test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:      
      matrix:        
       node-version: [11.x]

    steps:      
    # Use the node version specified in the strategy    
    - name: Use Node.js ${{ matrix.node-version }}      
      uses: actions/setup-node@v1      
      with:        
        node-version: ${{ matrix.node-version }}

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Git checkout
      uses: actions/checkout@v2

    # Install packages
    - name: Install packages
      run: |
        yarn install
        
    # Install packages
    - name: Install packages
      run: |
       cd TANSACS-trial/Frontend/tansacs/
       yarn install

    # Build an optimized production build
    - name: Production build      
      run: |        
        unset CI
        yarn build

    # Deploy to the S3 server
    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.tansac-website-react }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        SOURCE_DIR: "TANSACS-trial/Frontend/tansacs"
